import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { ROLES } from '../utils/rbac';
import { hackathonApi } from '../services/api';

export default function HackathonsPage() {
  const { user } = useAuth(); const [hackathons, setHackathons] = useState([]); const [registrations, setRegistrations] = useState([]); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [isLoading, setIsLoading] = useState(true);
  const load = async () => { setIsLoading(true); try { const requests = [hackathonApi.list()]; if (user?.role === ROLES.PARTICIPANT) requests.push(hackathonApi.myRegistrations()); const [events, mine] = await Promise.all(requests); setHackathons(events.data.hackathons || []); setRegistrations(mine?.data || []); } catch (e) { setError(e.message || 'Unable to load hackathons.'); } finally { setIsLoading(false); } };
  useEffect(() => { load(); }, [user?.id]);
  const act = async (action, success) => { setError(''); setNotice(''); try { await action(); setNotice(success); await load(); } catch (e) { setError(e.message); } };
  const registrationFor = (id) => registrations.find((item) => (item.hackathon?._id || item.hackathon) === id && item.status !== 'cancelled');
  return <motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} className="space-y-6"><section className="rounded-[3rem] border border-white/70 bg-white/70 p-8 shadow-xl backdrop-blur"><p className="text-sm uppercase tracking-[.35em] text-forest/60">Discover experiences</p><h1 className="mt-3 text-4xl font-semibold">Browse remarkable hackathons</h1></section>{notice && <p className="rounded-2xl bg-cream/70 p-4 text-forest">{notice}</p>}{error && <p className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</p>}<div className="grid gap-6 lg:grid-cols-2">{isLoading && <p>Loading hackathons...</p>}{!isLoading && hackathons.map((hackathon) => { const registration = registrationFor(hackathon._id); return <article key={hackathon._id} className="rounded-[2rem] border border-white/70 bg-white/80 p-6 shadow-lg backdrop-blur"><div className="flex justify-between gap-3"><span className="rounded-full bg-forest/10 px-3 py-1 text-sm font-semibold">{hackathon.theme}</span><span className="text-sm text-forest/70">{hackathon.status}</span></div><h2 className="mt-4 text-2xl font-semibold">{hackathon.title}</h2><p className="mt-3 text-forest/70">{hackathon.description}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3 text-sm"><span>Prize: {hackathon.prizePool}</span><div className="flex items-center gap-2"><Link to={`/hackathons/${hackathon._id}`} className="rounded-full bg-forest px-4 py-2 font-semibold text-cream">Details</Link>{user?.role === ROLES.PARTICIPANT && (registration ? <div className="flex items-center gap-2"><span className="rounded-full bg-olive/50 px-3 py-2 font-semibold capitalize">{registration.status}</span><button onClick={() => act(() => hackathonApi.cancelRegister(hackathon._id), 'Registration cancelled.')} className="rounded-full border border-forest/20 px-3 py-2 font-semibold">Cancel</button></div> : <button disabled={!hackathon.registrationOpen} onClick={() => act(() => hackathonApi.register(hackathon._id), 'Registration submitted for approval.')} className="rounded-full border border-forest/20 px-4 py-2 font-semibold disabled:opacity-50">Register</button>)}</div></div></article>; })}</div></motion.div>;
}