import { motion } from 'framer-motion';
import { FaArrowRight, FaBolt, FaChartLine, FaQuoteLeft, FaShieldAlt, FaTrophy, FaUsers } from 'react-icons/fa';
import { Link } from 'react-router-dom';

const featured = [
  { title: 'Future of Health', theme: 'HealthTech', prize: '$25,000', mode: 'Hybrid' },
  { title: 'Open Cities Challenge', theme: 'Civic Innovation', prize: '$18,000', mode: 'Online' },
  { title: 'Code for Climate', theme: 'Sustainability', prize: '$20,000', mode: 'In person' },
];
const upcoming = [
  { title: 'GreenTech Sprint', theme: 'Climate Innovation', date: 'Sep 14' },
  { title: 'AI Builders Jam', theme: 'Applied Intelligence', date: 'Oct 02' },
  { title: 'Fintech Forge', theme: 'Next Gen Finance', date: 'Oct 18' },
];
const stats = [['Active Hackathons', '240+'], ['Projects Submitted', '18k'], ['Global Builders', '92k']];
const winners = [['NovaGrid AI', 'Team Orbit', 'Grand Prize · 2025'], ['CivicMint', 'North Star Labs', 'Best Social Impact · 2025'], ['AquaSense', 'Blue Horizon', 'People’s Choice · 2024']];
const testimonials = [['HackVerse made our first national hackathon feel effortless. Every role had exactly what it needed.', 'Aarav Mehta', 'Community Organizer'], ['The review workflow gave us clear feedback and helped our team turn a prototype into a real product.', 'Sana Khan', 'Participant & Winner'], ['Scoring was structured, fast, and transparent. I could focus entirely on the projects.', 'Riya Sharma', 'Judge']];
const glass = 'rounded-[2rem] border border-white/70 bg-white/70 p-6 shadow-lg backdrop-blur';

export default function LandingPage() {
  return <div className="space-y-8">
    <motion.section initial={{ opacity: 0, y: 50 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} className="relative overflow-hidden rounded-[3rem] bg-gradient-to-br from-forest via-[#0a5239] to-[#033225] p-8 text-cream shadow-premium sm:p-12 lg:p-16">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(255,255,255,0.2),transparent_30%)]" />
      <div className="relative grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><div className="inline-flex items-center rounded-full border border-white/25 bg-white/10 px-4 py-2 text-sm"><FaBolt className="mr-2" /> Where ambitious ideas take off</div><h1 className="mt-6 font-display text-5xl leading-none sm:text-6xl lg:text-8xl">Build the idea that changes everything.</h1><p className="mt-6 max-w-xl text-lg text-cream/80">Find meaningful challenges, collaborate with great people, and turn your best prototype into a real impact story.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/signup" className="rounded-full bg-cream px-6 py-3 font-semibold text-forest">Join HackVerse</Link><Link to="/hackathons" className="rounded-full border border-white/30 px-6 py-3 font-semibold">Explore hackathons</Link></div></div><motion.div animate={{ y: [0, -10, 0] }} transition={{ duration: 4, repeat: Infinity }} className="rounded-[2.5rem] border border-white/20 bg-white/10 p-6 backdrop-blur"><div className="rounded-[2rem] bg-cream/95 p-6 text-forest"><div className="flex justify-between rounded-full bg-forest px-4 py-2 text-sm text-cream"><span>Live challenge</span><span>09:41:12</span></div><div className="mt-6 rounded-2xl bg-cream p-4 shadow"><p className="text-sm text-forest/60">Winner spotlight</p><b className="text-2xl">NovaGrid AI</b></div><div className="mt-4 rounded-2xl bg-forest p-4 text-cream"><p className="text-sm text-cream/70">Projects this week</p><b className="text-3xl">+84%</b></div></div></motion.div></div>
    </motion.section>

    <section className={glass}><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[.3em] text-forest/60">Featured hackathons</p><h2 className="mt-2 text-3xl font-semibold">Big ideas need a great stage</h2></div><Link to="/hackathons" className="inline-flex items-center gap-2 font-semibold">Explore all <FaArrowRight /></Link></div><div className="mt-7 grid gap-4 lg:grid-cols-3">{featured.map((item, i) => <motion.article whileHover={{ y: -5 }} key={item.title} className="relative overflow-hidden rounded-[2rem] border border-forest/10 bg-gradient-to-br from-cream via-white to-olive/60 p-6"><span className="absolute right-5 top-3 text-5xl text-forest/10">0{i + 1}</span><p className="text-sm uppercase tracking-[.2em] text-forest/60">{item.theme}</p><h3 className="mt-3 text-2xl font-semibold">{item.title}</h3><div className="mt-8 flex justify-between text-sm"><span>{item.mode}</span><b>{item.prize}</b></div></motion.article>)}</div></section>

    <section className="grid gap-4 md:grid-cols-3">{stats.map(([label, value]) => <div key={label} className={glass}><div className="text-3xl font-semibold">{value}</div><div className="mt-2 text-forest/70">{label}</div></div>)}</section>

    <section className={glass}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm uppercase tracking-[.3em] text-forest/60">Upcoming events</p><h2 className="mt-2 text-3xl font-semibold">Save your next challenge</h2></div><Link to="/hackathons" className="font-semibold">Browse all</Link></div><div className="mt-7 grid gap-4 lg:grid-cols-3">{upcoming.map((event) => <article key={event.title} className="rounded-[2rem] border border-forest/10 bg-gradient-to-br from-cream to-olive p-6"><p className="text-sm uppercase tracking-[.2em] text-forest/60">{event.theme}</p><h3 className="mt-3 text-2xl font-semibold">{event.title}</h3><div className="mt-6 flex justify-between"><span>{event.date}</span><Link to="/hackathons" className="rounded-full bg-forest px-4 py-2 text-sm font-semibold text-cream">View event</Link></div></article>)}</div></section>

    <section><div className="mb-5"><p className="text-sm uppercase tracking-[.3em] text-forest/60">Why participate</p><h2 className="mt-2 text-3xl font-semibold">More than a competition</h2></div><div className="grid gap-4 lg:grid-cols-3">{[[<FaUsers />, 'Meet your collaborators', 'Join mission-driven challenges with mentors, teammates, and sponsors.'], [<FaChartLine />, 'Grow with momentum', 'Track your progress from a first sketch to a polished submission.'], [<FaShieldAlt />, 'Build with confidence', 'Clear roles and transparent feedback make every experience fair.']].map(([icon, title, text]) => <motion.article whileHover={{ y: -4 }} key={title} className={glass}><div className="inline-flex rounded-full bg-forest/10 p-3 text-forest">{icon}</div><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-3 text-forest/70">{text}</p></motion.article>)}</div></section>

    <section className="rounded-[3rem] bg-gradient-to-br from-forest to-[#073c2d] p-8 text-cream shadow-premium"><div className="flex items-end justify-between"><div><p className="text-sm uppercase tracking-[.3em] text-cream/60">Previous winners</p><h2 className="mt-2 text-3xl font-semibold">Ideas that went further</h2></div><FaTrophy className="text-4xl text-olive" /></div><div className="mt-7 grid gap-4 md:grid-cols-3">{winners.map(([project, team, award]) => <article key={project} className="rounded-[2rem] border border-white/15 bg-white/10 p-6"><p className="text-sm text-cream/60">{award}</p><h3 className="mt-3 text-2xl font-semibold">{project}</h3><p className="mt-2 text-cream/75">{team}</p></article>)}</div></section>

    <section className={glass}><p className="text-sm uppercase tracking-[.3em] text-forest/60">Testimonials</p><h2 className="mt-2 text-3xl font-semibold">Built for people who build</h2><div className="mt-7 grid gap-4 lg:grid-cols-3">{testimonials.map(([quote, name, role]) => <figure key={name} className="rounded-[2rem] border border-forest/10 bg-cream/55 p-6"><FaQuoteLeft className="text-forest/30" /><blockquote className="mt-4 leading-relaxed text-forest/80">“{quote}”</blockquote><figcaption className="mt-5"><b>{name}</b><div className="text-sm text-forest/60">{role}</div></figcaption></figure>)}</div></section>
  </div>;
}