import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { hackathonApi, teamApi } from '../services/api';

const field = 'mt-2 w-full rounded-xl border border-forest/15 bg-cream/50 px-3 py-2 outline-none focus:border-forest';
const button = 'rounded-full bg-forest px-4 py-2 text-sm font-semibold text-cream';

export default function TeamPage() {
  const [hackathons, setHackathons] = useState([]); const [teams, setTeams] = useState([]); const [availableTeams, setAvailableTeams] = useState([]); const [name, setName] = useState(''); const [hackathon, setHackathon] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = async () => { try { const [events, myTeams, openTeams] = await Promise.all([hackathonApi.list(), teamApi.list({ mine: true }), teamApi.list()]); setHackathons(events.data.hackathons || []); setTeams(myTeams.data || []); setAvailableTeams(openTeams.data || []); } catch (e) { setError(e.message); } };
  useEffect(() => { load(); }, []);
  const act = async (fn, success) => { setError(''); try { await fn(); setMessage(success); await load(); } catch (e) { setError(e.message); } };
  return <motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
    <section className="rounded-[3rem] border border-white/70 bg-white/80 p-8 shadow-xl backdrop-blur"><p className="text-sm uppercase tracking-[0.35em] text-forest/60">Team hub</p><h1 className="mt-3 text-4xl font-semibold">Coordinate your squad</h1><p className="mt-3 text-forest/70">Create a team, join an open team, invite collaborators, or update your team name.</p></section>
    {message && <p className="rounded-2xl bg-cream/70 p-4 text-forest">{message}</p>}{error && <p className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-[2rem] border border-white/70 bg-white/75 p-6 shadow-lg"><h2 className="text-2xl font-semibold">Create a team</h2><form onSubmit={(e) => { e.preventDefault(); act(() => teamApi.create({ name, hackathon }), 'Team created and sent for approval.'); }} className="mt-4"><label className="text-sm">Team name<input required value={name} onChange={(e) => setName(e.target.value)} className={field} /></label><label className="mt-3 block text-sm">Hackathon<select required value={hackathon} onChange={(e) => setHackathon(e.target.value)} className={field}><option value="">Choose an event</option>{hackathons.map((item) => <option key={item._id} value={item._id}>{item.title}</option>)}</select></label><button className={`${button} mt-4`}>Create team</button></form></section><section className="rounded-[2rem] border border-white/70 bg-white/75 p-6 shadow-lg"><h2 className="text-2xl font-semibold">My teams</h2><div className="mt-4 space-y-3">{teams.map((team) => <TeamCard key={team._id} team={team} act={act} />)}{teams.length === 0 && <p className="text-forest/70">You are not in a team yet.</p>}</div></section></div>
    <section className="rounded-[2rem] border border-white/70 bg-white/75 p-6 shadow-lg"><h2 className="text-2xl font-semibold">Teams you can join</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{availableTeams.filter((team) => team.status !== 'rejected').map((team) => <div key={team._id} className="rounded-xl bg-cream/50 p-4"><b>{team.name}</b><p className="mt-1 text-sm text-forest/60">{team.hackathon?.title || 'Hackathon'} · {team.members?.length || 0} members</p><button onClick={() => act(() => teamApi.join(team._id), 'You joined the team.')} className={`${button} mt-3`}>Join team</button></div>)}</div></section>
  </motion.div>;
}
function TeamCard({ team, act }) { const [edit, setEdit] = useState(team.name); const [email, setEmail] = useState(''); return <div className="rounded-xl bg-cream/50 p-4"><b>{team.name}</b><span className="ml-2 text-sm text-forest/60">{team.status}</span><p className="mt-1 text-sm text-forest/60">{team.hackathon?.title || 'Hackathon'} · {team.members?.length || 0} members</p><div className="mt-3 flex flex-wrap gap-2"><input value={edit} onChange={(e) => setEdit(e.target.value)} className="rounded-lg border border-forest/15 bg-white px-2 py-1 text-sm"/><button onClick={() => act(() => teamApi.update(team._id, { name: edit }), 'Team details updated.')} className="rounded-full border border-forest/20 px-3 py-1 text-sm">Save</button><button onClick={() => act(() => teamApi.leave(team._id), 'You left the team.')} className="rounded-full border border-forest/20 px-3 py-1 text-sm">Leave</button></div><div className="mt-2 flex gap-2"><input placeholder="Invite by email" value={email} onChange={(e) => setEmail(e.target.value)} className="rounded-lg border border-forest/15 bg-white px-2 py-1 text-sm"/><button onClick={() => act(() => teamApi.invite(team._id, email), 'Member added to your team.')} className="rounded-full border border-forest/20 px-3 py-1 text-sm">Invite</button></div></div>; }