import axios from 'axios';
const api = axios.create({ baseURL: '/api', headers: { 'Content-Type': 'application/json' } });
api.interceptors.request.use((config) => { const token = localStorage.getItem('hackverse-token'); if (token) config.headers.Authorization = `Bearer ${token}`; return config; });
api.interceptors.response.use((response) => response, (error) => { const err = new Error(error.response?.data?.message || error.message || 'Something went wrong'); err.status = error.response?.status; return Promise.reject(err); });
export default api;
export const hackathonApi = {
  list: (params) => api.get('/hackathons', { params }), get: (id) => api.get(`/hackathons/${id}`), create: (data) => api.post('/hackathons', data), update: (id, data) => api.put(`/hackathons/${id}`, data), remove: (id) => api.delete(`/hackathons/${id}`), register: (id) => api.post(`/hackathons/${id}/register`), cancelRegister: (id) => api.delete(`/hackathons/${id}/register`), myRegistrations: () => api.get('/hackathons/registrations/mine'), managedRegistrations: () => api.get('/hackathons/registrations/managed'), updateRegistration: (hackathonId, registrationId, status) => api.patch(`/hackathons/${hackathonId}/registrations/${registrationId}`, { status }), toggleRegistration: (id, open) => api.patch(`/hackathons/${id}/registration`, { open }), assignJudges: (id, judgeIds) => api.patch(`/hackathons/${id}/judges`, { judgeIds }), publishWinners: (id, winnerSubmissionIds) => api.patch(`/hackathons/${id}/winners`, { winnerSubmissionIds }),
};
export const authApi = { login: (email, password) => api.post('/auth/login', { email, password }), register: (payload) => api.post('/auth/register', payload), me: () => api.get('/auth/me'), updateProfile: (data) => api.put('/auth/profile', data) };
export const teamApi = { list: (params) => api.get('/teams', { params }), create: (data) => api.post('/teams', data), join: (id) => api.post(`/teams/${id}/join`), update: (id, data) => api.put(`/teams/${id}`, data), invite: (id, email) => api.post(`/teams/${id}/invite`, { email }), leave: (id) => api.post(`/teams/${id}/leave`), approve: (id) => api.patch(`/teams/${id}/approve`), reject: (id) => api.patch(`/teams/${id}/reject`) };
export const submissionApi = { list: (params) => api.get('/submissions', { params }), create: (data) => api.post('/submissions', data), update: (id, data) => api.put(`/submissions/${id}`, data), leaderboard: (params) => api.get('/submissions/leaderboard', { params }) };
export const reviewApi = { submit: (data) => api.post('/reviews', data), assignments: () => api.get('/reviews/assignments') };
export const adminApi = { users: (params) => api.get('/users', { params }), analytics: () => api.get('/users/analytics'), judges: () => api.get('/users/judges'), blockUser: (id) => api.patch(`/users/${id}/block`), updateRole: (id, role) => api.patch(`/users/${id}/role`, { role }), deleteUser: (id) => api.delete(`/users/${id}`) };
export const dashboardApi = { stats: () => api.get('/dashboard/stats') };